sudo: required

services:
  - docker

branches:
  only:
  - master

before_install:
  - docker build -t sassy .

script:
  - docker run sassy

deploy:
  provider: script
  script: test $TRAVIS_PULL_REQUEST = "false" && test $TRAVIS_BRANCH = "master" && docker run -e TWINE_USERNAME=$TWINE_USERNAME -e TWINE_PASSWORD=$TWINE_PASSWORD sassy bash deploy.sh
  on:
    branch: master