sudo: required

services:
  - docker

branches:
  only:
  - master

before_install:
  - docker build -t sassy .

script:
  - docker run sassy

deploy:
  provider: script
  script: docker run -e TWINE_USERNAME=$TWINE_USERNAME -e TWINE_PASSWORD=$TWINE_PASSWORD sassy bash deploy.sh
  skip_cleanup: true
  on:
    branch: master